### PR TITLE
Allow arrays to be treated as Array FormGroup

### PR DESCRIPTION
**Pull request by aitorllj93**
Allow arrays to be treated as FormGroup of Array besides FormArray

### CODE REVIEW

**Comment by KostyaTretyak** [comment]
Hi, @d3v0ps. Please explain why you need this change?

**Comment by aitorllj93** [comment]
Hi @KostyaTretyak when working with custom components, some of them accept array fields instead of the typical ngFor + FormArray way, so I guess I need to set those fields as FormGroup instead

**Comment by KostyaTretyak** [comment]
Any examples?

**Comment by aitorllj93** [comment]
@KostyaTretyak I can't provide you real examples because I faced the issue on my company's code, but basically, for example you could have a component without ControlValueAccesor support (or even with it) that takes an array as input data, like for example an editable table. The way the interface behaves, makes not possible to attach an array as a formControl for a single component, what would be the approach if my input handles array data, like a multi select or a tag input?

Also IMO, the types should only add typing safety to the Angular Forms, not disallowing you to do something you could do with the original implementation

**Comment by KostyaTretyak** [comment]
Have you tried using `Control` type?

```ts
import { Control } from '@ng-stack/forms';

// Form Model
interface Person {
  id: number;
  name: string;
  birthDates: Control<Date[]>; // Here should be FormControl, instead of a FormArray
}
```

**Comment by aitorllj93** [comment]
I will try it, sounds as an interesting alternative instead of casting it with `as unknown as FormArray`, the only drawback I can see is that I would need to create specific models for the form instead of being able to use the auto-generated ones from OpenApi

**Comment by KostyaTretyak** [comment]
As [docs says](https://github.com/KostyaTretyak/ng-stack/tree/master/projects/forms#automatically-detect-appropriate-types-for-form-controls), if the form model interface comes from an external library, you can do the following:

```ts
import { FormBuilder, Control } from '@ng-stack/forms';

// External Form Model
interface ExternalPerson {
  id: number;
  name: string;
  birthDate: Date;
}

const formConfig: ExternalPerson = {
  id: 123,
  name: 'John Smith',
  birthDate: new Date(1977, 6, 30),
};

interface Person extends ExternalPerson {
  birthDate: Control<Date>;
}


const fb = new FormBuilder();
const form = fb.group<Person>(formConfig); // `Control<Date>` type is compatible with `Date` type.

const birthDate: Date = form.value.birthDate; // `Control<Date>` type is compatible with `Date` type.
```

**Pull request closed without merging**
